# Site settings
title: moni
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  なんてブログだ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robinkun.github.io" # the base hostname & protocol for your site
twitter_username: NeoAdeyo
github_username:  robinkun
keep_files: [js, youtube, game/mygame]

# Build settings
markdown: kramdown
